### ISSUE TITLE
The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by mosentest** [youlookwhat/ByRecyclerView#24]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5150)
        at android.view.ViewGroup.addView(ViewGroup.java:4979)
        at android.view.ViewGroup.addView(ViewGroup.java:4919)
        at android.view.ViewGroup.addView(ViewGroup.java:4892)
        at me.jingbin.library.ByRecyclerView.setStateView(ByRecyclerView.java:925)
        at cn.yh.sdmp.ui.message.MessageFragment.initView(MessageFragment.java:121)
        at com.zipper.lib.base.fragment.BaseFragment.onViewCreated(BaseFragment.java:72)
        at com.zipper.lib.base.fragment.BaseRvFragment.onViewCreated(BaseRvFragment.java:46)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)

**Comment by youlookwhat** [comment]
好的 我处理一下

**Comment by youlookwhat** [comment]
我这边没有复现，不过我处理了一下，可以引用最新的试试 
 - version : 1.1.5

**Comment by mosentest** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youlookwhat/ByRecyclerView"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月1日(星期一) 下午4:57
收件人:&nbsp;"youlookwhat/ByRecyclerView"<ByRecyclerView@noreply.github.com&gt;;
抄送:&nbsp;"Dispirited、"<709847739@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youlookwhat/ByRecyclerView] The specified child already has a parent. You must call removeView() on the child's parent first. (#24)



 我这边没有复现，不过我处理了一下，可以引用最新的试试
  version : 1.1.5

**Comment by youlookwhat** [comment]
@moz1q1 可以了吗，没事的话我关闭了哈
