### ISSUE TITLE
flexbox布局没法添加emptyview

### ISSUE THREAD

**Issue by muzidudu** [youlookwhat/ByRecyclerView#25]
报错如下
`E/>>>>>>: java.lang.ClassCastException: androidx.recyclerview.widget.RecyclerView$LayoutParams cannot be cast to com.google.android.flexbox.FlexItem
        at com.google.android.flexbox.FlexboxHelper.calculateFlexLines(FlexboxHelper.java:438)
        at com.google.android.flexbox.FlexboxHelper.calculateHorizontalFlexLines(FlexboxHelper.java:242)
E/>>>>>>:     at com.google.android.flexbox.FlexboxLayoutManager.updateFlexLines(FlexboxLayoutManager.java:940)
        at com.google.android.flexbox.FlexboxLayoutManager.onLayoutChildren(FlexboxLayoutManager.java:716)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
        at android.view.View.measure(View.java:25448)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6884)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25448)
        at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1599)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:585)
        at android.view.View.measure(View.java:25448)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6884)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25448)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6884)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:25448)
E/>>>>>>:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6884)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25448)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6884)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25448)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6884)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25448)
E/>>>>>>:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6884)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25448)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6884)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:739)
        at android.view.View.measure(View.java:25448)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3361)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2203)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2460)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1934)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8127)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at com.kongzue.baseframework.BaseFrameworkSettings$1.run(BaseFrameworkSettings.java:52)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
W/Looper: Loop again would have the queued messages be executed before this one completed.
`

**Comment by youlookwhat** [comment]
好的，我看看

**Comment by youlookwhat** [comment]
已添加对应demo，主要是处理FlexboxLayoutManager部分，对应处理代码：
[FlexBoxActivity.java](https://github.com/youlookwhat/ByRecyclerView/blob/master/app/src/main/java/me/jingbin/byrecyclerview/activity/FlexBoxActivity.java)

1.使用自定义的 ByFlexboxLayoutManager
2.不能设置加载更多
3.显示EmptyView后不能再加载数据

需要将ByFlexboxLayoutManager拷贝到自己项目中，然后先接口请求数据加载内容，没有内容的话显示EmptyView

**Comment by muzidudu** [comment]
👌 好的,感谢

> 已添加对应demo，主要是处理FlexboxLayoutManager部分，对应处理代码：
> [FlexBoxActivity.java](https://github.com/youlookwhat/ByRecyclerView/blob/master/app/src/main/java/me/jingbin/byrecyclerview/activity/FlexBoxActivity.java)
> 
> 1.使用自定义的 ByFlexboxLayoutManager
> 2.不能设置加载更多
> 3.显示EmptyView后不能再加载数据
> 
> 需要将ByFlexboxLayoutManager拷贝到自己项目中，然后先接口请求数据加载内容，没有内容的话显示EmptyView
